SCR_MissionHeader {
 World "{C25366E6DB7C3E2E}Worlds/S1LENCE_Worlds/Test World/TestWorld.ent"
 m_sName "Test World of Podval"
 m_sAuthor "SILENCE"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}