SCR_MissionHeader {
 World "{28C8B8DFA3C2EC67}Worlds/Ryba/BarzanMapRemake/TvT_Castle_Assault_BarzanMapRemake/TvT_Castle_Asault_BarzanMapRemake.ent"
 m_sName "Штурм замка"
 m_sAuthor "Ryba"
 m_sPath "Missions/Ryba/TvT_Castle_Assault_BarzanMapRemake.conf"
 m_sDescription "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
 m_iStartingHours 10
}