SCR_MissionHeader {
 World "{485E1E4DCA6414B3}Worlds/Vanya/ChernarusMinus/TVT_VECVERVPULKOVO_chernarus/TVT_VECVERVPULKOVO_chernarus.ent"
 m_sName "Горка"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}