SCR_MissionHeader {
 World "{E1C94BF152E7B2D8}Worlds/Vanya/ChernarusMinus/TVT_MER_KAMYSHOVO_chernarus/TVT_MER_KAMYSHOVO_chernarus.ent"
 m_sName "Мэр Камышово"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}