SCR_MissionHeader {
 World "{1C8ED84945E51577}Worlds/Vanya/ChernarusMinus/TVT_BEREZINO_Chernarus/BEREZINO.ent"
 m_sName "Ад в Березино"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}