SCR_MissionHeader {
 World "{B278B39823DCD823}Worlds/Vanya/ChernarusMinus/TVT_SHTURM_chernarus/TVT_SHTURM_chernarus.ent"
 m_sName "Штурм Электрозаводска"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}