SCR_MissionHeader {
 World "{485E1E4DCA6414B3}Worlds/Vanya/ChernarusMinus/TVT_GORKA_Chernarus/TVT_GORKA_Chernarus.ent"
 m_sName "Вилла Губы"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}