SCR_MissionHeader {
 World "{2A4123271D93E485}Worlds/Vanya/ChernarusMinus/TVT_OboronaSobora_Chernarus/TVT_OboronaSobora_Chernarus.ent"
 m_sName "Оборона Собора"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}