SCR_MissionHeader {
 World "{1DB1139E28FE7332}Worlds/Vanya/ChernarusMinus/TVT_KheSanh_V2_chernarus/TVT_KheSanh_V2_chernarus.ent"
 m_sName "Khe Sanh"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}