SCR_MissionHeader {
 World "{C6415B75058B43EC}Worlds/Vanya/Everon/TVT_Princes_Everone/Princes.ent"
 m_sName "Oil Rig"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}