SCR_MissionHeader {
 World "{AA37EFE8988AA6BC}Worlds/Vanya/Utes/TVT_OSTROV_Utes/OSTROV.ent"
 m_sName "Остров в океане"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}