SCR_MissionHeader {
 World "{21190B7667875BBD}Worlds/Vanya/Takistan/TVT_Navali_Takistan/Navali.ent"
 m_sName "Президент Такистана"
 m_sAuthor "Vane4ka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}