SCR_MissionHeader : "{3232D77CF313C850}Missions/NoTimeZZZ/TvT_Base.conf" {
 World "{0F356FE420734EB1}Worlds/NoTmeZZZ/TvT_AnizayThreeZone_Anizay/TvT_AnizayThreeZone_Anizay.ent"
 m_sName "Спящая ячейка"
}