SCR_MissionHeader : "{3232D77CF313C850}Missions/NoTimeZZZ/TvT_Base.conf" {
 World "{3F8BF6E003428518}Worlds/NoTmeZZZ/TvT_ShootingInZarichne_Zarichne/TvT_ShootingInZarichne_Zarichne.ent"
 m_sName "Битва за Заричный"
}