SCR_MissionHeader : "{3232D77CF313C850}Missions/NoTimeZZZ/TvT_Base.conf" {
 World "{70E3AA5FB7E07E8F}Worlds/NoTmeZZZ/TvT_LatestPictures_Zargabad/TvT_LatestPictures_Zargabad.ent"
 m_sName "Последние сники"
}