SCR_MissionHeader {
 World "{DE53507628216893}Worlds/DimOchka/Frontier/TvT_BalticStrike_Frontier/TvT_BalticStrike_Frontier.ent"
 m_sName "Балтийский удар"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}