SCR_MissionHeader {
 World "{7C7432B9F156F3AA}Worlds/DimOchka/TvT_30Seconds_Kunar/TvT_30Seconds_Kunar.ent"
 m_sName "30 секунд"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}