SCR_MissionHeader {
 World "{2467EED1F59C990F}Worlds/DimOchka/Zimnitrita/TvT_Depot_Zimnitrita/TvT_Depot_Zimnitrita.ent"
 m_sName "Депо"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}