SCR_MissionHeader {
 World "{41E7E2C169462FD0}Worlds/DimOchka/TvT_TargernNumberOne_Zimnitrita/TvT_TargernNumberOne_Zimnitrita.ent"
 m_sName "Цель номер один"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}