SCR_MissionHeader {
 World "{B53774740BE235CE}Worlds/DimOchka/Frontier/TvT_BrokenArrow_Frontier/TvT_BrokenArrow_Frontier.ent"
 m_sName "Сломанная стрела"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}