SCR_MissionHeader {
 World "{F68E7325911944F0}Worlds/DimOchka/ChernarusMinus/TvT_TheOnlyWay_ChernarusMinus/TvT_TheOnlyWay_ChernarusMinus.ent"
 m_sName "Единственный путь"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}