SCR_MissionHeader {
 World "{19791A7586B1A45E}Worlds/DimOchka/Gogland/TvT_Gogland89_Gogland/TvT_Gogland89_Gogland.ent"
 m_sName "Гогланд-89"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}