SCR_MissionHeader {
 World "{D02407169C72ABD8}Worlds/DimOchka/Kolguev/TvT_FindAndDestroy_Cain/TvT_FindAndDestroy_Cain.ent"
 m_sName "Найти и уничтожить"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}