SCR_MissionHeader {
 World "{2FC36E14BF0DD177}Worlds/DimOchka/TvT_PhantomPain_Cain/TvT_PhantomPain_Cain.ent"
 m_sName "Человек, который продал мир"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}