SCR_MissionHeader {
 World "{DEFEF2D33AA7183F}Worlds/DimOchka/Kunar/TvT_BountyHunters_Kunar/TvT_BountyHunters_Kunar.ent"
 m_sName "Охотники за головами"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}