SCR_MissionHeader {
 World "{CF6EFCBEDBD5B69B}Worlds/DimOchka/ChernarusMinus/TvT_NewOrder_ChernarusMinus/TvT_NewOrder_ChernarusMinus.ent"
 m_sName "Новый заказ"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}