SCR_MissionHeader {
 World "{CA0C3CBF6F4924C5}Worlds/DimOchka/TvT_HeavyArtillery_AlHadra/TvT_HeavyArtillery_AlHadra.ent"
 m_sName "Тяжелая артиллерия"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}