SCR_MissionHeader {
 World "{40815EB46FC5A6A8}Worlds/DimOchka/Faircroft/TvT_OutskirtsSeaHaven_Faircroft/TvT_OutskirtsSeaHaven_Faircroft.ent"
 m_sName "Окрестности Seahaven"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}