SCR_MissionHeader {
 World "{BC2F636C6AEFDFA0}Worlds/DimOchka/TvT_MomentOfTruth_Gogland/TvT_MomentOfTruth_Gogland.ent"
 m_sName "Момент истины"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}