SCR_MissionHeader {
 World "{DDD5DC5231A10214}Worlds/DimOchka/Kolguev/TvT_OpJustCause_Cain/TvT_OpJustCause_Cain.ent"
 m_sName "Операция \"Правое дело\""
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}