SCR_MissionHeader {
 World "{EDF8B6F590164B02}Worlds/DimOchka/Kolguev/TvT_RedDawn_Cain/TvT_RedDawn_Cain.ent"
 m_sName "Красная заря"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}