SCR_MissionHeader {
 World "{DE9E943C951EF432}Worlds/DimOchka/TvT_EscapeFromNorth_Zimnitrita/TvT_EscapeFromNorth_Zimnitrita.ent"
 m_sName "Escape from Zimnitrita"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}