SCR_MissionHeader {
 World "{B14E0D1012D27072}Worlds/DimOchka/Faircroft/TvT_ScotlandHighlands_Faircroft/TvT_ScotlandHighlands_Faircroft.ent"
 m_sName "Шотландское нагорье"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}