SCR_MissionHeader {
 World "{7A9FDDD5669B8A9B}Worlds/DimOchka/Zimnitrita/TvT_IronStrike_Zimnitrita/TvT_IronStrike_Zimnitrita.ent"
 m_sName "Железный удар"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}