SCR_MissionHeader {
 World "{ABB1E4C6C78DBE87}Worlds/DimOchka/TvT_KolguevFriends_Cain/TvT_KolguevFriends_Cain.ent"
 m_sName "Колгуевские ребята"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}