SCR_MissionHeader {
 World "{306B363DF392A749}Worlds/DimOchka/Faircroft/TvT_AgainstTheOdds_Faircroft/TvT_AgainstTheOdds_Faircroft.ent"
 m_sName "Вопреки всему"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}