SCR_MissionHeader {
 World "{9ECA130550968CC2}Worlds/DimOchka/Ruha/TvT_MovingMountains_Ruha/TvT_MovingMountains_Ruha.ent"
 m_sName "Сдвигая горы"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}