SCR_MissionHeader {
 World "{64415D73C17375A7}Worlds/DimOchka/Faircroft/TvT_FreedomPrice_Faircroft/TvT_FreedomPrice_Faircroft.ent"
 m_sName "Цена свободы"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}