SCR_MissionHeader {
 World "{99896EEA35997192}Worlds/DimOchka/Ruha/TvT_JacksHouse_Ruha/TvT_JacksHouse_Ruha.ent"
 m_sName "Дом, который построил Джек"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}