SCR_MissionHeader {
 World "{C72AA6309B415474}Worlds/DimOchka/Ruha/TvT_Supermarket_Ruha/TvT_Supermarket_Ruha.ent"
 m_sName "Супермаркет"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}