SCR_MissionHeader {
 World "{240972C3AD1BF85F}Worlds/DimOchka/TvT_QuietHaven_Faircroft/TvT_QuietHaven_Faircroft.ent"
 m_sName "Тихая гавань"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}