SCR_MissionHeader {
 World "{867EB2538965749F}Worlds/DimOchka/TvT_Invasion_Faircroft/TvT_Invasion_Faircroft.ent"
 m_sName "Вторжение"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}