SCR_MissionHeader {
 World "{857E87BFF79ADE76}Worlds/DimOchka/ChernarusMinus/TvT_TwoDirections_ChernarusMinus/TvT_TwoDirections_ChernarusMinus.ent"
 m_sName "Два направления"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}