SCR_MissionHeader {
 World "{817A4E1BFAE84DF2}Worlds/DimOchka/ChernarusMinus/TvT_Meeting_ChernarusMinus/TvT_Meeting_ChernarusMinus.ent"
 m_sName "Встреча"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}