SCR_MissionHeader {
 World "{A8C7531ACE2EA73E}Worlds/DimOchka/TvT_NegotiationTheory_Anizay/TvT_NegotiationTheory_Anizay.ent"
 m_sName "Теория переговоров"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}