SCR_MissionHeader {
 World "{E04E6A961C77995B}Worlds/DimOchka/Zimnitrita/TvT_MeteorHotel_Zimnitrita/TvT_MeteorHotel_Zimnitrita.ent"
 m_sName "Отель \"Метеор\""
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}