SCR_MissionHeader {
 World "{B472E68DD9E792F7}Worlds/DimOchka/Anizay/TvT_ATruthwortlyMan_Anizay/TvT_ATruthwortlyMan_Anizay.ent"
 m_sName "Надежный человек"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}