SCR_MissionHeader {
 World "{03D1F1433C8A8ABA}Worlds/DimOchka/TvT_TheBog_Anizay/TvT_TheBog_Anizay.ent"
 m_sName "Болото"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}