SCR_MissionHeader {
 World "{4D38E145A06C6A3A}Worlds/DimOchka/ChernarusMinus/TvT_ScavRush_ChernarusMinus/TvT_ScavRush_ChernarusMinus.ent"
 m_sName "Откуда у диких минометы?"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}