SCR_MissionHeader {
 World "{06F6F13B9236894A}Worlds/DimOchka/TvT_TheFateOfBritain_FairCroft/TvT_TheFateOfBritain_FairCroft_1.ent"
 m_sName "Судьба Британии"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}