SCR_MissionHeader {
 World "{29BB0A6BC34AFDCA}Worlds/DimOchka/Frontier/TvT_SovietKatok_Frontier/TvT_SovietKatok_Frontier.ent"
 m_sName "Советский каток"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}