SCR_MissionHeader {
 World "{9BEFB841C17AF7C5}Worlds/DimOchka/Zimnitrita/TvT_TheEnemyAtTheGates_Zimnitrita/TvT_TheEnemyAtTheGates_Zimnitrita.ent"
 m_sName "Враг у ворот"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}