SCR_MissionHeader {
 World "{BF440DCAAD624241}Worlds/DimOchka/Novka/TvT_Signal_Novka/TvT_Signal_Novka.ent"
 m_sName "Сигнал"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}