SCR_MissionHeader {
 World "{2A7F9E19A19D78E4}Worlds/DimOchka/TvT_CheckpointBravo_Anizay/TvT_CheckpointBravo_Anizay.ent"
 m_sName "Чекпоинт \"Браво\""
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}