SCR_MissionHeader {
 World "{00D953CBEDC5F072}Worlds/DimOchka/TvT_JacksHouse_RuhaWinter/TvT_JacksHouse_RuhaWinter.ent"
 m_sName "Дом, который построил Джек"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}