SCR_MissionHeader {
 World "{C011CC6E337277FC}Worlds/DimOchka/Faircroft/TvT_AshBastion_Faircroft/TvT_AshBastion_Faircroft.ent"
 m_sName "Пепельный бастион"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}