SCR_MissionHeader {
 World "{68E20376ECDD9F4B}Worlds/DimOchka/Gogland/TvT_GoglandCrysis_Gogland/TvT_GoglandCrysis_Gogland.ent"
 m_sName "Гогландский кризис"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}