SCR_MissionHeader {
 World "{D1C6D451DF6DFA58}Worlds/DimOchka/TvT_RoadToTakistan_Kunar/TvT_RoadToTakistan_Kunar.ent"
 m_sName "Дорога на Такистан"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}