SCR_MissionHeader {
 World "{D06FC30D89C7A674}Worlds/DimOchka/Anizay/TvT_ThirtyPalms_Anizay/TvT_ThirtyPalms_Anizay.ent"
 m_sName "30 пальм"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}