SCR_MissionHeader {
 World "{4090FDB06FF8D72D}Worlds/DimOchka/TvT_KorengalValley_Kunar/TvT_KorengalValley_Kunar.ent"
 m_sName "Долина Коренгал"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}