SCR_MissionHeader {
 World "{4043D8E9DF3B5A40}Worlds/DimOchka/TvT_FIAHunter_Eden/TvT_FIAHunter_Eden.ent"
 m_sName "Охотник на ФИАшников"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}