SCR_MissionHeader {
 World "{CD0DB8609E294AA9}Worlds/DimOchka/Faircroft/TvT_LastChance_Faircroft/TvT_LastChance_Faircroft.ent"
 m_sName "Последний шанс"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}