SCR_MissionHeader {
 World "{5D99A74A24EB081D}Worlds/DimOchka/ChernarusMinus/TvT_ScavRush_Chernarus_GM/TvT_ScavRush_Chernarus_GM.ent"
 m_sName "Откуда у диких минометы?"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}