SCR_MissionHeader {
 World "{ECA2E0FED8BD3353}Worlds/DimOchka/TvT_NationalTreasure_Anizay/TvT_NationalTreasure_Anizay.ent"
 m_sName "Сокровище нации"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}