SCR_MissionHeader {
 World "{4A6C30B43263CC17}Worlds/DimOchka/TvT_DangerZone_Ruha/TvT_DangerZone_Ruha.ent"
 m_sName "Опасная зона"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}