SCR_MissionHeader {
 World "{09F6A12724A89F2B}Worlds/DimOchka/TvT_Inception_Zimnitria/TvT_Inception_Zimnitria.ent"
 m_sName "Начало"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}