SCR_MissionHeader {
 World "{8F0A74CAC7F667B9}Worlds/DimOchka/Takistan/TvT_NewCharacter_Takistan/TvT_NewCharacter_Takistan.ent"
 m_sName "Новый персонаж"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}