SCR_MissionHeader {
 World "{B70636B17A579AC5}Worlds/DimOchka/Anizay/TvT_Sputnik_Anizay/TvT_Sputnik_Anizay.ent"
 m_sName "В небо"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}