SCR_MissionHeader {
 World "{53313E49B8741BBC}Worlds/DimOchka/Anizay/TvT_OilRush_Anizay/TvT_OilRush_Anizay.ent"
 m_sName "Нефтяная лихорадка"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}