SCR_MissionHeader {
 World "{068A9036BBD61AF2}Worlds/DimOchka/TvT_ThinRedLine_RuhaWinter/TvT_ThinRedLine_RuhaWinter.ent"
 m_sName "Тонкая красная линия"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}