SCR_MissionHeader {
 World "{232C198C66EB9AFE}Worlds/DimOchka/Zimnitrita/TvT_PassportControl_Zimnitrita/TvT_PassportControl_Zimnitrita.ent"
 m_sName "Паспортный контроль"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}