SCR_MissionHeader {
 World "{153915DBEF005CC0}Worlds/TEVAK/TVT_Strike_from_the_sky_Takistan/TVT_Strike_from_the_sky_Takistan.ent"
 m_sName "Удар с неба"
 m_sAuthor "TEVAK"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}