SCR_MissionHeader {
 World "{FA4886948D44C11E}Worlds/TEVAK/TVT_Black_Forest_NSOF_Berzan/TVT_Black_Forest_NSOF_Berzan.ent"
 m_sName "Чёрный лес"
 m_sAuthor "TEVAK"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}