SCR_MissionHeader {
 World "{172113D3C855F11A}Worlds/TEVAK/TVT_GSM_Wakeisland/TVT_GSM_Wakeisland.ent"
 m_sName "Склад ГСМ"
 m_sAuthor "TEVAK"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}