SCR_MissionHeader {
 World "{EB97D490387B0AA0}TvT_Military_Town_3_Anizay.ent"
 m_sName "Военный городок №3"
 m_sAuthor "TEVAK"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}