SCR_MissionHeader {
 World "{12972E80E12DCFDA}Worlds/BlackJokeR/ChernarusMinus/TvT_OperationSteelRails_ChernarusMinus/TvT_OperationSteelRails_ChernarusMinus.ent"
 m_sName "Операция \"Стальные рельсы\""
 m_sAuthor "BlackJokeR"
 m_sDetails "PODVAL Event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}