SCR_MissionHeader {
 World "{6DAE94A5F0891895}Worlds/BlackJokeR/KhanhTrung/TvT_CheckMate_KhanhTrung/TvT_CheckMate_KhanhTrung.ent"
 m_sAuthor "BlackJokeR"
 m_sDetails "PODVAL Event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}