SCR_MissionHeader {
 World "{991551A05551EE9B}Worlds/BlackJokeR/Rokostrov/TvT_OperationBurstFlame_Rokostrov/TvT_OperationBurstFlame_Rokostrov.ent"
 m_sName "Операция \"Вспышка пламени\""
 m_sAuthor "BlackJokeR"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}