SCR_MissionHeader {
 World "{B6FED61ADDEB7B0A}Worlds/Givapich/TvT_bazar_AL_Hadra/TvT_bazar_AL_Hadra.ent"
 m_sName "Alhadra Blackout"
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}