SCR_MissionHeader : "{FBA88995A676B0C6}Missions/Biryuk/sTvT_Base.conf" {
 World "{2781ED2E4A4C27E8}Worlds/Biryuk/Faircroft/sTvT_deja_vu_Faircroft/sTvT_deja_vu_Faircroft.ent"
 m_sName "Дежавю"
 m_sGameMode "sTvT"
}