SCR_MissionHeader : "{FBA88995A676B0C6}Missions/Biryuk/STvT_Base.conf" {
 World "{AF0AA9E20CAC23EC}Worlds/Biryuk/Zarichne/TvT_NorthernFront_Zarichne/TvT_NorthernFront_Zarichne.ent"
 m_sName "Северный фронт Заречное"
 m_sDescription "ВС США форсировали реку и готовятся к захвату НП Бердяевку"
 m_sGameMode "sTvT"
}