SCR_MissionHeader : "{886836A3B32E997B}Missions/Biryuk/TvT_Base.conf" {
 World "{4BCBDF544F9F7B25}Worlds/Biryuk/Takistan/TvT_Mulladdost_Takistan/TvT_Mulladdost_Takistan.ent"
 m_sName "Пафос в Мулладосте"
 m_sPath ""
 m_sDescription "Опять штурмуем кишлак"
}