SCR_MissionHeader : "{886836A3B32E997B}Missions/Biryuk/TvT_Base.conf" {
 World "{A67BA6F150339DEA}Worlds/Biryuk/Zarichne/OkopnyyReyv_Zarichne.ent"
 m_sName "Окопный рейв"
 m_sDescription "Все старое, но по новому"
}