SCR_MissionHeader {
 World "{A4EE7C6B873C6194}Worlds/sean/cherno/TvT_ScuffleInChernogorsk_Cherno/TvT_ScuffleInChernogorsk_Cherno.ent"
 m_sName "Потасовка в Черногорске"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}