SCR_MissionHeader {
 World "{4BB5550C2C67B81F}Worlds/sean/zimnitrita/TvT_AndruhanovAssault_Zimnitrita/TvT_AndruhanovAssault_Zimnitrita.ent"
 m_sName "Осада Андрюханова"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}