SCR_MissionHeader {
 World "{B7236AB42F4BD9C1}Worlds/sean/takistan/TvT_TakistanOil_Takistan/TvT_TakistanOil_Takistan.ent"
 m_sName "Сырая Нефть"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}