SCR_MissionHeader {
 World "{4A84CA1CDE2676D3}Worlds/sean/eden/TvT_MontignacAssault_Eden/TvT_MontignacAssault_Eden.ent"
 m_sName "Осада Монтиньяка"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}