SCR_MissionHeader {
 World "{2F71DEDA76BC4CD3}Worlds/sean/belleauwood/TvT_12Hours_BelleauWood/TvT_12Hours_BelleauWood.ent"
 m_sName "12 Часов"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}