SCR_MissionHeader {
 World "{1DAD866826720AFD}Worlds/sean/alhadra/TvT_Drough_AlHadra/TvT_Drough_AlHadra.ent"
 m_sName "Засуха"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}