SCR_MissionHeader {
 World "{BBB5740246CB2A3E}Worlds/sean/eden/TvT_FreedomWantness_Eden.ent"
 m_sName "Жажда свободы"
 m_sAuthor "sean"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}