SCR_MissionHeader {
 World "{AFDAAC0E9C6FB21E}Worlds/Banan/DenaliBase/TvT_Aeroport_Denali.ent"
 m_sName "Забытый аэропорт"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}