SCR_MissionHeader {
 World "{7DF8CA4A32458D6E}Worlds/Banan/NizlaIsland/TvT_PigeonrestFlag_NizlaIsland.ent"
 m_sName "Битва за церковь"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}