SCR_MissionHeader {
 World "{928D279BD80DF700}Worlds/Banan-Drongo/PvP_Hill55_KhanhTrung/PvP_Hill55_KhanhTrung.ent"
 m_sName "Высота 55"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}