SCR_MissionHeader {
 World "{E95D1880EC86FCF2}Worlds/Banan/Seitenbuch - Germany/TvT_DayStorm_Seitenbuch.ent"
 m_sName "Дневной штурм"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}