SCR_MissionHeader {
 World "{68EB835870512947}Worlds/Banan/NizlaIsland/PigeonrestFlag/TvT_PigeonrestFlag_NizlaIsland.ent"
 m_sName "Битва за церковь"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}