SCR_MissionHeader {
 World "{A8D1388C785D8552}Worlds/Banan/Everon/TvT_LigthHouse_Everon/TvT_LigthHouse_Everon.ent"
 m_sName "Битва за маяк"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}