SCR_MissionHeader {
 World "{63A9337B3C406B81}Worlds/Banan/Gogland/TvT_NarkoMission_gogland.ent"
 m_sName "Барон Карлеонэ"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}