SCR_MissionHeader {
 World "{5B5A58812117DB4B}Worlds/Banan-Drongo/PvP_TheLastBell_Kalguev/PvP_TheLastBell_Kalguev.ent"
 m_sName "Последний звонок"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}