SCR_MissionHeader {
 World "{7E07EFABDD3E8A91}Worlds/Banan/Everon/TvT_MeauxAssault_Everon/TvT_MeauxAssault_Everon.ent"
 m_sName "Осада Мо"
 m_sAuthor "Peroi"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}