SCR_MissionHeader {
 World "{7DD09712BBC8752B}Worlds/Banan/Everon/TvT_MeauxAssault_EVeron/TvT_MeauxAssault_Everon.ent"
 m_sName "Осада Мо"
 m_sAuthor "Banan/Peroi"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}