SCR_MissionHeader {
 World "{50E56C56849DB863}Worlds/Banan-Drongo/PvP_PersonaNonGrata_Everon/PvP_PersonaNonGrata_Everon.ent"
 m_sName "Персона Южного Эверона"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}