SCR_MissionHeader {
 World "{2B22C3FB89E0B05B}My_mission/Cherno/TVT_Berezino_Chernorus.ent"
 m_sName "Оборона промзоны"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}