SCR_MissionHeader {
 World "{B6E0D0E167F9BC7F}Worlds/Banan-Drongo/PvP_VDV_Everon/PvP_VDV_Everon.ent"
 m_sName "ВДВ"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}