SCR_MissionHeader {
 World "{210D51323DB5A2BD}Worlds/Banan/Vietnam/TvT_Hill55_Vietnam.ent"
 m_sName "Высота 55"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}