SCR_MissionHeader {
 World "{D4B31C52B1705BF4}Worlds/Banan-Drongo/PvP_Convoy_Eden/PvP_Convoy_Eden.ent"
 m_sName "Смертельный путь"
 m_sAuthor "Banan/Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}