SCR_MissionHeader {
 World "{D3D8D6BA301193F1}Worlds/Banan/Anizay/TvT_MinaretMission_Anizay.ent"
 m_sName "Русские стены - Американские пули"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}