SCR_MissionHeader {
 World "{C1B7DEBCAC4AE0A8}Worlds/Banan/Barzan/TvT_PortMission_Barzan.ent"
 m_sName "Порт"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}