SCR_MissionHeader {
 World "{F1C35231C58A1D6D}Worlds/Banan/Zarichne/TvT_DyrkaMission_Zarichne.ent"
 m_sName "Баталия в Заричном"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}