SCR_MissionHeader {
 World "{A4E4757736899BD7}Worlds/Banan/ChernarusMinus/Voenka/TvT_VoenkaKamenoe_Chernorus.ent"
 m_sName "Битва за Каменое"
 m_sAuthor "Banan"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}