SCR_MissionHeader {
 World "{E33C264BFE330128}Worlds/Banan/Proverka/TVT_Googland_Mission_Googland/TVT_Googland_Mission_Googland.ent"
 m_sName "Битва за военную базу"
 m_sAuthor "Nero"
 m_sDescription "Миссия только для рандом ивентов"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}