SCR_MissionHeader {
 World "{B7E3228227EF7BE0}Worlds/Potato/Cain/Megagonka_Cain.ent"
 m_sName "Мегагонка"
 m_sAuthor "SaiD_потато"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}