SCR_MissionHeader {
 World "{8318E4EE133B1CC2}Worlds/Random/rTvT_Random_Zargabad/rTvT_Random_Zargabad.ent"
 m_sName "Рандом на Заргабаде"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}