SCR_MissionHeader {
 World "{03482532F897EBAC}Worlds/Random/rTvT_Random_Novka/TvT_Random_Novka.ent"
 m_sName "Рандом на Новке"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}