SCR_MissionHeader {
 World "{F2EF9586C750EF6C}Worlds/Random/rTvT_RandomMission_Cherno/rTvT_RandomMission_Cherno.ent"
 m_sName "Битва за Заречное"
 m_sAuthor "[GG] Shax"
 m_sDescription "Рандомные ивенты СИЛАААА"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}