SCR_MissionHeader {
 World "{DBC22E2FDF34FB2B}Worlds/Random/rTvT_RandomMission_Eden/rTvT_RandomMission_Eden.ent"
 m_sName "Битва за Эверон"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}