SCR_MissionHeader {
 World "{83BEEB220932C5F1}Worlds/Random/rTvT_RandomMission_Zarichne/rTvT_RandomMission_Zarichne.ent"
 m_sName "Битва за Заречное"
 m_sAuthor "[GG] Shax"
 m_sDescription "Рандомные ивенты СИЛАААА"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}