SCR_MissionHeader {
 World "{6FEA3F6B2BD389AE}Worlds/Random/rTvT_RandomMission_Arland_WCS/rTvT_RandomMission_Arland_WCS.ent"
 m_sName "Битва за Арланд"
 m_sAuthor "SILENCE"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}