SCR_MissionHeader {
 World "{548E3E833F010456}Worlds/Random/rTvT_RandomMission_Barzan/rTvT_RandomMission_Barzan.ent"
 m_sName "Битва за Барзан"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}