SCR_MissionHeader {
 World "{490FC2DE1E281A2F}Worlds/Gidra/Shiza/TvT_Talkan_Anizay/TvT_Talkan_Anizay.ent"
 m_sName "Талчёк"
 m_sAuthor "Gidra"
 m_sDetails "Podval event"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}