SCR_MissionHeader {
 World "{B30B46F5A88A189F}Worlds/Gidra/Zargabad/TvT_Terminal_Zargabad/TvT_Terminal_Zargabad.ent"
 m_sName "Терминал"
 m_sAuthor "Gidra"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}