SCR_MissionHeader {
 World "{490FC2DE1E281A2F}Worlds/Gidra/Shiza/TvT_Talkan_Anizay/TvT_Talkan_Anizay.ent"
 m_sName "Талкан"
 m_sAuthor "Gidra"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}