SCR_MissionHeader {
 World "{3E28BBDFB9A33609}Worlds/Horizon/Kunar/TvT_AirportDefend_Kunar/TvT_AirportDefend_Kunar.ent"
 m_sName "Оборона Аэропорта"
 m_sAuthor "Horizon"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}