SCR_MissionHeader {
 World "{08CC068FBAB35DE8}Worlds/Horizon/Kunar/TvT_KishlakDefend_Kunar/TvT_KishlakDefend.ent"
 m_sName "Оборона кишлака"
 m_sAuthor "[RSA]HRZN (Horizon)"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}