SCR_MissionHeader {
 World "{140950D9BEF85BFB}Worlds/Muravei/TvT_Gogland_Small/TvT_Gogland_Small.ent"
 m_sName "Остров Сайво, Гогланд"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}