SCR_MissionHeader {
 World "{7929AD170E2225EE}Worlds/Muravei/TvT_Kolguev_Ostrov/TvT_BattaliaForOstrov_Kolguev.ent"
 m_sName "База на Скалистом"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}