SCR_MissionHeader {
 World "{0419C058DC714469}Worlds/Muravei/TvT_Bellau_Zamok_Small/TvT_Bellau_Zamok_Small.ent"
 m_sName "Замок Элуп"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}