SCR_MissionHeader {
 World "{0B2CA46D368617C1}Worlds/Muravei/TvT_Kunar_Small/TvT_Kunar_Small.ent"
 m_sName "Нангалам, Кунар"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}