SCR_MissionHeader {
 World "{A1F6AEDC949E5973}Worlds/Muravei/TvT_htLand_Small/TvT_htLand_Small.ent"
 m_sName "Атака на Хунор"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}