SCR_MissionHeader {
 World "{B13FA09B42784948}Worlds/Muravei/TvT_Chernagorsk_ChernarusMinus/TvT_Chernagorsk_ChernarusMinus.ent"
 m_sName "Штурм Черногорска"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}