SCR_MissionHeader {
 World "{53A896A6CF518D1E}Worlds/Muravei/TvT_Zimnitrita_TruhaMilitaryBase/TvT_Zimnitrita_TruhaMilitaryBase.ent"
 m_sName "Военная база в Трухе"
 m_sAuthor "Muravei"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}