SCR_MissionHeader {
 World "{CEE07C92252EC799}Worlds/Banan-Drongo/PvP_TheSiege/PvP_TheSiege.ent"
 m_sName "Осада!"
 m_sAuthor "Drongo"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}