SCR_MissionHeader {
 World "{3251650EEF1011E9}Worlds/Horizon/Kolguev/TvT_Mountain_defend_Kolguev/TvT_Mountain_defend_Kolguev.ent"
 m_sName "Оборона горы"
 m_sAuthor "Horizon"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}