SCR_MissionHeader {
 World "{8D482DA180D9935B}Worlds/Draka/Chernorus/TVT_ChernorusMission_Chernorus/TvT_ChernorusMissionDraka_Chernorus.ent"
 m_sName "Бензовозы Болот"
 m_sAuthor "DimOchka"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}