SCR_MissionHeader : "{01734F96FCA40FBB}Missions/Djungarik/TvT_Base.conf" {
 World "{305311F9BAF75835}Worlds/Djungarik/TvT_Heart_desert_Takistan/TvT_Heart_desert_Takistan.ent"
 m_sName "Сердце Пустыни"
}