SCR_MissionHeader {
 World "{4C86251865345A14}Worlds/mafia/Arland/TvT_LagerPartyzan_Arland.ent"
 m_sName "Лагерь Партизан"
 m_sAuthor "Mafia"
 m_sPath ""
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}