SCR_MissionHeader {
 World "{94935796729C8A3C}Worlds/Random/rTvT_Random_Novka/TvT_Random_Novka.ent"
 m_sAuthor "Biryuk"
 m_sPath "Missions/Biryuk"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}