SCR_MissionHeader {
 World "{DCD31A49CF3B7944}Worlds/mafia/Cherno/TvT_BitvaZaGorky_ChernoMinus/TvT_BitvaZaGorky_ChernoMinus.ent"
 m_sName "Битва за Горку"
 m_sAuthor "mafia"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}