SCR_MissionHeader {
 World "{94935796729C8A3C}Worlds/mafia/Kolguev/TvT_ruiniHamertina_Kolguev/TvT_ruiniHamertina_Kolguev.ent"
 m_sName "Руины Хамертина"
 m_sAuthor "Mafia"
 m_sPath ""
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}