SCR_MissionHeader {
 World "{CB885AC1C3AE228A}Worlds/mafia/Eden/TvT_BitvaZaHesreit_Eden.ent"
 m_sName "Битва за Хэшрейт"
 m_sAuthor "Mafia"
 m_sPath ""
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}