SCR_MissionHeader {
 World "{143F062605AC824F}Worlds/mafia/ChernoRussia/TvT_BitvaZaGorky/TvT_BitvaZaGorky.ent"
 m_sAuthor "Biryuk"
 m_sPath "Missions/Biryuk"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}