SCR_MissionHeader {
 World "{044C5C5F5EEAA660}TVT_CHERNO/unnamed.ent"
 m_sName "Битва за Горку"
 m_sAuthor "mafia"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}