SCR_MissionHeader {
 World "{A0917CBB47A557F9}Worlds/mafia/Faircroft Islands/TvT_OperationHammer_FaircroftIslands.ent"
 m_sName "Операция Молот"
 m_sAuthor "Mafia"
 m_sPath ""
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}