SCR_MissionHeader {
 World "{4223CE127FB0A774}Worlds/RamboKZ/TvT_4AS_Eden/TvT_4AS_Eden.ent"
 m_sName "Битва за Руху"
 m_sAuthor "RamboKZ"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_iStartingHours 9
}