SCR_MissionHeader {
 m_sName "Тест название"
 m_sAuthor "RamboKZ"
 m_sPath "Missions/RamboKZ"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_iStartingHours 12
}