SCR_MissionHeader : "{78A5A23FCBEED74E}Missions/RamboKZ/TvT.conf" {
 World "{95FC0E96C68F0CE9}Worlds/RamboKZ/TvT_LastBenzRandom_htLand/TvT_LastBenzRandom_htLand.ent"
 m_sName "Последний бензин (Random)"
 m_iStartingHours 13
}