SCR_MissionHeader : "{78A5A23FCBEED74E}Missions/RamboKZ/TvT.conf" {
 World "{1BFC664E4AF981F5}Worlds/RamboKZ/TvT_OperationHotel_Anizay/TvT_OperationHotel_Anizay.ent"
 m_sName "Операция «Отель»"
 m_sDescription "Ликвидация Хасан Али Бабаха"
 m_sIcon "{A5E940EBF093C0BD}UI/Textures/MissionLoadingScreens/GM_Anizay.edds"
 m_sLoadingScreen "{A5E940EBF093C0BD}UI/Textures/MissionLoadingScreens/GM_Anizay.edds"
 m_sPreviewImage "{A5E940EBF093C0BD}UI/Textures/MissionLoadingScreens/GM_Anizay.edds"
}