SCR_MissionHeader : "{78A5A23FCBEED74E}Missions/RamboKZ/TvT.conf" {
 World "{5FB1F9AC1279BFB0}Worlds/RamboKZ/TvT_ProtectTulzovich_Marnivka/TvT_ProtectTulzovich_Marnivka.ent"
 m_sName "Протык Тулзовича"
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 13
}