SCR_MissionHeader : "{78A5A23FCBEED74E}Missions/RamboKZ/TvT.conf" {
 World "{6250AF182EA1D349}Worlds/RamboKZ/TvT_GromihaloPodmishki_Chernarus/TvT_GromihaloPodmishki_Chernarus.ent"
 m_sName "Громыхало из Подмышки"
}