SCR_MissionHeader {
 World "{B2E5381C37979A22}Worlds/RamboKZ/TvT_OperationIronTide_Faircroft/TvT_OperationIronTide_Faircroft.ent"
 m_sName "Операция «Железный прилив»"
 m_sAuthor "RamboKZ"
 m_sPath "Missions/RamboKZ"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_iStartingHours 12
}