SCR_MissionHeader {
 World "{0F3D3B1A5A02ACC2}Worlds/RamboKZ/TvT_Tihina_Colguev/TvT_Tihina_Colguev.ent"
 m_sName "Тишина"
 m_sAuthor "GRIf feat. RamboKZ"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}