SCR_MissionHeader {
 World "{754A9CE0D1D86EF1}missions/TvT_Tihina_Colguev/TvT_Tihina_Colguev.ent"
 m_sName "Тишина"
 m_sAuthor "GRIf"
 m_sDetails "Podval event"
 m_sIcon "{1CFD3E0BA0151B8F}UI/Textures/MissionLoadingScreens/Reforger_HQCIcon_Kolguyev_UI.edds"
 m_sLoadingScreen "{12FA5C592434407B}UI/Textures/MissionLoadingScreens/SP01_PreviewImage_UI.edds"
 m_sPreviewImage "{269BD5A5DF17B042}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Kolguyev_UI.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}