SCR_MissionHeader : "{78A5A23FCBEED74E}Missions/RamboKZ/TvT.conf" {
 World "{9FED99BB81681568}Worlds/RamboKZ/TvT_CaptureHeliBase_htLand/TvT_CaptureHeliBase_htLand.ent"
 m_sName "Захват «Вертолетной базы»"
 m_iStartingHours 13
 m_iStartingMinutes 30
}