SCR_MissionHeader {
 World "{DC148C3DCAB5FB47}Worlds/Horizon/BelleauWood/TvT_TrenchWarfare_BelleauWood/TvT_TrenchWarfare_BelleauWood.ent"
 m_sName "Окопная битва"
 m_sAuthor "Horizon"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}