SCR_MissionHeader {
 World "{C785702EF0C78D1C}Worlds/Horizon/BelleauWood/TvT_CastleDefend_BelleauWood/TvT_CastleDefend_BelleauWood.ent"
 m_sName "Оборона замка"
 m_sAuthor "Horizon"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}