SCR_MissionHeader {
 World "{D1EA93ABE079B878}Worlds/Gubastus/TvT_TradeIllusion_Ruha/TvT_TradeIllusion_Ruha.ent"
 m_sName "Иллюзия обмена"
 m_sAuthor "Gubastus/RamboKZ"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_bOverrideScenarioTimeAndWeather 1
 m_iStartingHours 12
}