SCR_MissionHeader {
 World "{168AC6777278966C}Worlds/Gubastus/TvT_SpecialCabbageOperation_Bystrany/TvT_SpecialCabbageOperation_Bystrany.ent"
 m_sName "Специальная Капустная Операция"
 m_sAuthor "Gubastus"
 m_sDescription "ВС РФ начинают СКО против ГМО капусты, выращенной ЧСО при поддержке ВС США."
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}