SCR_MissionHeader {
 World "{632E1470E86DBC0B}Worlds/Gubastus/TvT_ThreeWays_Ruha/TvT_ThreeWays_Ruha.ent"
 m_sName "Три пути"
 m_sAuthor "Gubastus"
 m_sDescription "Нападение ВС США на одну из трех баз ВС РФ."
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}