SCR_MissionHeader {
 World "{DF6962C4F7BB1CE0}Worlds/Givapich/Hamland/TvT_Firebase_Hamland/TvT_Firebase_Hamland.ent"
 m_sName "Огневая база"
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}