SCR_MissionHeader : "{2F13372F6633FB71}Missions/Givapich/TvT_Base.conf" {
 World "{A52BC34290262D07}Worlds/Givapich/Eden/TvT_fuelshortage_Eden_fix/TvT_fuelshortage_Eden.ent"
 m_sName "Топливный дефицит"
}