SCR_MissionHeader {
 World "{8D672FA07A72CECF}Worlds/Givapich/TvT_fuelshortage_Eden/TvT_fuelshortage_Eden.ent"
 m_sName "Топливный дефицит"
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}