SCR_MissionHeader : "{C65FEE2FE88071EA}Missions/Givapich/TvT_Base.conf" {
 World "{8D672FA07A72CECF}Worlds/Givapich/Eden/TvT_fuelshortage_Eden/TvT_fuelshortage_Eden.ent"
 m_sName "Топливный дефицит"
}