SCR_MissionHeader {
 World "{25420F742EC376BB}Worlds/Givapich/TvT_Toplivnykonflikt_Ringkollen/TvT_Toplivnykonflikt_Ringkollen.ent"
 m_sName "Топливный конфликт "
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}