SCR_MissionHeader {
 World "{F3F67B84CEB6D855}Worlds/Givapich/Galicia/TvT_PoslednyayaSmena_Galicia/TvT_PoslednyayaSmena_Galicia.ent"
 m_sName "Последняя смена"
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
}