SCR_MissionHeader {
 World "{F3F67B84CEB6D855}Worlds/Givapich/TvT_zahvat_Galicia/TvT_zahvat_Galicia.ent"
 m_sName "Последняя смена"
 m_sAuthor "Гивапыч"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}