SCR_MissionHeader : "{C65FEE2FE88071EA}Missions/Givapich/TvT_Base.conf" {
 World "{25420F742EC376BB}Worlds/Givapich/Ringkollen/TvT_Toplivnykonflikt_Ringkollen/TvT_Toplivnykonflikt_Ringkollen.ent"
 m_sName "Топливный конфликт"
}