SCR_MissionHeader {
 World "{480F8646EA1970B6}Worlds/Givapich/Anizay/TvT_Cavecity_Anizay/TvT_Cavecity_Anizay.ent"
 m_sName "Нефтяной джекпот"
 m_sAuthor "Admiral Cracker/Гивапыч"
 m_sDetails "Podval event"
 m_sIcon ""
 m_sLoadingScreen ""
 m_sPreviewImage ""
 m_sGameMode "TvT"
 m_iPlayerCount 128
 m_WCS_Core_Settings WCS_Core_Settings "{69EB1EB50A40DA71}" {
 }
}